### PR TITLE
Add wavelet transform

### PR DESCRIPTION
**Pull request by mgrub**
Implement requested functionality of #86

### CODE REVIEW

**Comment by BjoernLudwigPTB** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- PyDynamic/misc/testsignals.py  2
- PyDynamic/uncertainty/propagate_filter.py  14
- PyDynamic/uncertainty/propagate_DWT.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/PyDynamic/PyDynamic/pullRequest?prid=4507536&bid=15191290)

**Comment by BjoernLudwigPTB** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- PyDynamic/uncertainty/propagate_DWT.py  6
- PyDynamic/uncertainty/propagate_filter.py  14
- PyDynamic/misc/testsignals.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/PyDynamic/PyDynamic/pullRequest?prid=4507536&bid=15191290)

**Comment by BjoernLudwigPTB** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- PyDynamic/misc/testsignals.py  2
- PyDynamic/uncertainty/propagate_filter.py  14
- PyDynamic/uncertainty/propagate_DWT.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/PTB-PSt1/PyDynamic/pullRequest?prid=4507536&bid=15191290)

**Comment by BjoernLudwigPTB** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- PyDynamic/uncertainty/propagate_filter.py  14
- PyDynamic/misc/testsignals.py  2
- PyDynamic/uncertainty/propagate_DWT.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/PTB-PSt1/PyDynamic/pullRequest?prid=4507536&bid=15191290)

**Comment by BjoernLudwigPTB** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- PyDynamic/uncertainty/propagate_filter.py  14
- PyDynamic/misc/testsignals.py  2
- PyDynamic/uncertainty/propagate_DWT.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/PTB-PSt1/PyDynamic/pullRequest?prid=4507536&bid=15191290)

**Comment by mgrub** [comment]
Will be continued by PR #142

**Pull request closed without merging**
