### PR TITLE
Introduce contributing guide

### LINKED ISSUE #119: Provide a contribution guide and developer docs
Now that we test against all current Python versions, provide specific pinned requirements for all those versions and have some more or less established development workflows, practices and tools ready, we should document our way of developing PyDynamic. This should serve as a best practice example for research software engineering as well as help others to actually contribute or build upon PyDynamic.

We should include the Documentation build process into these and/or find a way to include these into the CI pipeline or GitHub feedback for PRs.

### PR DESCRIPTION
**Pull request by BjoernLudwigPTB**
This will resolve #119.

### CODE REVIEW

**Comment by mgrub** [comment]
Hey @BjoernLudwigPTB : The proposed contribution guide looks already very nice. 

Maybe, we also want to explicitly cover:
- implications of the chosen license on given contributions
- what needs to be to touched, if a new function/module gets added
- how to document new functionality (docstring, sphinx-structure, tests, examples, ...)

**Comment by BjoernLudwigPTB** [comment]
> Hey @BjoernLudwigPTB : The proposed contribution guide looks already very nice.
> 
> Maybe, we also want to explicitly cover:
> 
> * implications of the chosen license on given contributions
> * what needs to be to touched, if a new function/module gets added
> * how to document new functionality (docstring, sphinx-structure, tests, examples, ...)

@mgrub I added a couple of new sections. What do you think of when you say "implications of the chosen license on given contributions"?

**Comment by mgrub** [comment]
> @mgrub I added a couple of new sections. What do you think of when you say "implications of the chosen license on given contributions"?

I was thinking, that we may want to state the 2-3 most important aspects of LGPLv3. But I think, that the current way of stating the license in the `CONTRIBUTION.md` should be enough of a hint.

**Comment by mgrub** [comment]
This new section `Adding completely new functionality` covers just the things I was asking for 👍

**Comment by BjoernLudwigPTB** [comment]
> This new section `Adding completely new functionality` covers just the things I was asking for

Thanks! I will try to add a few words on a ReadTheDocs workflow extension and finally merge the changes afterwards.

**Comment by BjoernLudwigPTB** [comment]
This is going to get merged in few minutes...

**Pull request merged**
